export {
  adoptBackfill,
  backfillHeadwordSchema,
  backfillStateSchema,
  backfillStatus,
  createBackfillState,
  claimBackfillBatch,
  confirmBackfillTargets,
  discoverBackfill,
  discardBackfillSource,
  expireBackfillBatches,
  findBackfillLemma,
  markBackfillUnknown,
  renewBackfillBatch,
  replaceBackfillSource,
  resolveBackfillBatch,
  retryBackfillUnknown,
  type BackfillState,
} from "@huayi/learning-domain";
