export {
  adoptBackfillDismissed,
  backfillReviewBatches,
  discardAllBackfillReview,
  discardBackfillUnknown,
  backfillHeadwordSchema,
  backfillStateSchema,
  backfillStatus,
  createBackfillState,
  claimBackfillBatch,
  confirmBackfillTargets,
  discoverBackfill,
  discardAllBackfillUnresolved,
  discardBackfillSource,
  expireBackfillBatches,
  findBackfillLemma,
  findBackfillLemmaCandidates,
  markBackfillUnknown,
  renewBackfillBatch,
  replaceBackfillSource,
  resolveBackfillBatch,
  retryBackfillUnknown,
  type BackfillState,
} from "@huayi/learning-domain";
